### ISSUE TITLE
Save notebook as ipynb file

### ISSUE THREAD

**Issue by ccurtis7** [juniorfutang/cpmdata#4]
You will want to save this as a `.ipynb` file, otherwise interpreters outside Google CoLab won't be able to open the file. It's an easy fix. Just add `.ipynb` to the end of the file.

https://github.com/juniorfutang/qpm_data/blob/2cb445cf0120ce8ff40655f5d2c507f4b2461444/segmentation_1#L1-L4

**Comment by wongbria** [comment]
Done! Changed the filename by appending a .ipynb to be readable to other interpreters.
